# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0107_diagnosis_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='default_snomed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pppcemr.Snomed'),
        ),
    ]
