# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0110_workplanstepaddtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanstepaddtask',
            name='workplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pppcemr.Workplan'),
            preserve_default=False,
        ),
    ]
