# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0111_workplanstepaddtask_workplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanstepaddtask',
            name='encounter_owner_task',
            field=models.BooleanField(default=True),
        ),
    ]
