# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0113_auto_20160317_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PR', 'Practice Report'), ('OF', 'Office Report'), ('PA', 'Patient Report'), ('ER', 'Encounter Report'), ('AR', 'Assessment Report'), ('TR', 'Treatment Report'), ('UR', 'User Report')], default='PA', max_length=2)),
                ('report_template', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
