# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0114_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='assessment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='assessments',
            field=models.ManyToManyField(blank=True, null=True, to='pppcemr.Assessment'),
        ),
    ]
