# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0115_auto_20160322_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='encounter',
        ),
        migrations.AddField(
            model_name='assessment',
            name='encounters',
            field=models.ManyToManyField(to='pppcemr.Encounter'),
        ),
    ]
