# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0120_auto_20160406_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
