# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0121_auto_20160409_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='total_weight',
            new_name='weight_kg',
        ),
    ]
