# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0122_auto_20160425_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='kg', null=True),
        ),
    ]
