# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0123_auto_20160426_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineAntigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
    ]
