# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0124_vaccineantigen'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentoption',
            name='vaccine_antigens',
            field=models.ManyToManyField(blank=True, to='pppcemr.VaccineAntigen'),
        ),
    ]
