# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0127_auto_20160526_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccineantigen',
            options={'ordering': ['name']},
        ),
    ]
