# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0128_auto_20160526_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentoption',
            name='type',
            field=models.CharField(choices=[('NT', 'Note'), ('LB', 'Lab'), ('IL', 'In House Lab'), ('VI', 'Vital Signs'), ('RX', 'Drug Prescription'), ('PR', 'Procedure'), ('TS', 'Test'), ('HP', 'HPI and ROS'), ('PE', 'Physical Exam'), ('PF', 'PFSH'), ('FU', 'Follow-up Instructions'), ('VA', 'Vaccine / Immunization')], default='NT', max_length=2),
        ),
    ]
