# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0129_auto_20160526_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentoption',
            old_name='drug',
            new_name='drugs',
        ),
    ]
