# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0130_auto_20160526_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugadminoption',
            name='treatment_option',
        ),
        migrations.AddField(
            model_name='treatmentoption',
            name='drug_admins',
            field=models.ManyToManyField(blank=True, to='pppcemr.DrugAdminOption'),
        ),
    ]
