# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0131_auto_20160526_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='vaccine_lot_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='vaccine_site',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
