# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0132_auto_20160615_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentoption',
            name='vaccine_antigens',
        ),
        migrations.DeleteModel(
            name='VaccineAntigen',
        ),
    ]
