# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0137_auto_20160625_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentoption',
            name='vaccine_manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
