# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0138_treatmentoption_vaccine_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountertype',
            name='is_billed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encountertype',
            name='is_direct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encountertype',
            name='is_well',
            field=models.BooleanField(default=False),
        ),
    ]
