# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0140_encounter_is_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='EM_level',
            field=models.CharField(blank=True, choices=[('0', 'No bill'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5')], max_length=1, null=True),
        ),
    ]
