# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('pppcemr', '0142_auto_20160628_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicepreferences',
            name='group_to_receive_new_office_tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='office_task_owners', to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practicepreferences',
            name='group_to_receive_new_lab_tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_task_owners', to='auth.Group'),
        ),
    ]
