# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0144_auto_20160630_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_chart_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_telephone_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_waiting_room',
        ),
    ]
