# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0145_auto_20160630_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('E', 'Exam Room'), ('C', 'Chart Room'), ('T', 'Telephone Room'), ('W', 'Waiting Room')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
