# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0146_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicepreferences',
            options={'verbose_name_plural': 'Practice preferences'},
        ),
        migrations.AlterModelOptions(
            name='standardphysicalresults',
            options={'verbose_name_plural': 'Standard physical results'},
        ),
        migrations.AddField(
            model_name='encountertype',
            name='default_workplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pppcemr.Workplan'),
        ),
    ]
