# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0149_auto_20160701_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentoption',
            name='drug_allergy_cross_reactions',
            field=models.CharField(blank=True, help_text='Other medications that will react - separate with spaces', max_length=500, null=True),
        ),
    ]
