# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0152_treatment_file_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='file_attachment',
        ),
    ]
