# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0154_fileattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file_attachment',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/%h/%m/%s/'),
            preserve_default=False,
        ),
    ]
