# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0156_auto_20160707_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='final_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
