# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0158_practicepreferences_encounter_summary_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
