# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pppcemr', '0159_auto_20160710_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birth_medical_history',
            new_name='birth_history',
        ),
    ]
