from django.conf.urls import patterns, url, include


from . import views

urlpatterns = [
	# ex: /pppcemr/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /pppcemr/office/1/
    url(r'^office/(?P<pk>[0-9]+)/$', views.OfficeView.as_view(), name='office_detail'),
    # ex: /pppcemr/room/1/
    url(r'^room/(?P<pk>[0-9]+)/$', views.RoomView.as_view(), name='room_detail'),
    url(r'^room/(?P<pk>[0-9]+)/new_encounter/$', views.new_encounter, name='new_encounter'),
    url(r'^room/(?P<roomid>[0-9]+)/get_encounter/(?P<pk>[0-9]+)/$', views.get_encounter, name='get_encounter'),
    # ex: /pppcemr/encounter/1/
    url(r'^lookup_patient/$', views.lookup_patient, name='lookup_patient'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.PatientView.as_view(), name='patient_detail'),
    url(r'^patient/(?P<pk>[0-9]+)/get_weights/$', views.get_weights, name='get_weights'),
    url(r'^patient/(?P<pk>[0-9]+)/growthchart_weight/$', views.WeightChartView.as_view(), name='patient_growthchart_weight'),
    url(r'^patient/(?P<pk>[0-9]+)/growthchart_height/$', views.HeightChartView.as_view(), name='patient_growthchart_height'),
    url(r'^patient/(?P<pk>[0-9]+)/growthchart_bmi/$', views.BMIChartView.as_view(), name='patient_growthchart_bmi'),
    url(r'^patient/(?P<pk>[0-9]+)/vaccines/$', views.VaccinesView.as_view(), name='patient_vaccines'),
    url(r'^tasks/$', views.TaskList, name='task_list'),
    url(r'^messages/$', views.MessageList, name='message_list'),
    url(r'^messages/(?P<pk>[0-9]+)/$', views.MessageView.as_view(), name='message_detail'),
    url(r'^messages/send_message', views.send_message, name='send_message'),
    url(r'^messages/(?P<pk>[0-9]+)/close/$', views.close_message, name='close_message'),
    url(r'^messages/(?P<pk>[0-9]+)/reopen/$', views.reopen_message, name='reopen_message'),
    url(r'^messages/(?P<pk>[0-9]+)/reply/$', views.reply_message, name='reply_message'),
    url(r'^messages/(?P<pk>[0-9]+)/forward/$', views.forward_message, name='forward_message'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/send_message/$', views.send_message, name='send_encounter_message'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/send_message/$', views.send_message, name='send_assessment_message'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<treatmentid>[0-9]+)/send_message/$', views.send_message, name='send_assessment_treatment_message'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<treatmentid>[0-9]+)/send_message/$', views.send_message, name='send_encounter_treatment_message'),
    url(r'^encounter/(?P<pk>[0-9]+)/$', views.EncounterView.as_view(), name='encounter_detail'),
    url(r'^encounter/(?P<pk>[0-9]+)/edit/$', views.edit_encounter, name = 'edit_encounter'),
    url(r'^encounter/(?P<pk>[0-9]+)/add_workplan/$', views.add_workplan, name = 'add_workplan'),
    url(r'^encounter/(?P<pk>[0-9]+)/close/$', views.close_encounter, name = 'close_encounter'),
    url(r'^encounter/(?P<pk>[0-9]+)/reopen/$', views.reopen_encounter, name = 'reopen_encounter'),
    url(r'^encounter/(?P<pk>[0-9]+)/review/$', views.review_encounter, name = 'review_encounter'),
    url(r'^encounter/(?P<pk>[0-9]+)/summary/$', views.view_encounter_summary, name = 'view_encounter_summary'),
    url(r'^encounter/(?P<pk>[0-9]+)/edit_PMFSH/$', views.edit_PMFSH, name = 'edit_PMFSH'),
    url(r'^assessment/(?P<pk>[0-9]+)/$', views.AssessmentView.as_view(), name='assessment_detail'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<pk>[0-9]+)/$', views.AssessmentView.as_view(), name='encounter_assessment_detail'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<pk>[0-9]+)/close/$', views.close_assessment, name='close_assessment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<pk>[0-9]+)/change_snomed/$', views.change_snomed, name='change_snomed'),
    url(r'^encounter/(?P<pk>[0-9]+)/new_assessment/$', views.new_assessment, name='new_assessment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/new_treatment/$', views.new_treatment, name='new_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/add_treatment/(?P<pk>[0-9]+)/$', views.add_treatment, name='add_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/new_treatment/$', views.new_treatment, name='new_encounter_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<pk>[0-9]+)/$', views.TreatmentView.as_view(), name='encounter_treatment_detail'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<pk>[0-9]+)/$', views.TreatmentView.as_view(), name='treatment_detail'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<pk>[0-9]+)/edit_treatment/$', views.edit_treatment, name='edit_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<pk>[0-9]+)/edit_treatment/$', views.edit_treatment, name='edit_encounter_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<pk>[0-9]+)/close$', views.close_treatment, name='close_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<pk>[0-9]+)/close$', views.close_treatment, name='close_encounter_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<pk>[0-9]+)/reopen$', views.reopen_treatment, name='reopen_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<pk>[0-9]+)/reopen$', views.reopen_treatment, name='reopen_encounter_treatment'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<pk>[0-9]+)/edit_dosage$', views.edit_dosage, name='edit_dosage'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<pk>[0-9]+)/edit_dosage$', views.edit_dosage, name='edit_encounter_dosage'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/new_task/$', views.new_task, name='new_encounter_task'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<treatmentid>[0-9]+)/new_task/$', views.new_task, name='new_encounter_treatment_task'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<treatmentid>[0-9]+)/new_task/$', views.new_task, name='new_treatment_task'),
    url(r'^task/(?P<pk>[0-9]+)/edit/$', views.edit_task, name='edit_task'),
    url(r'^task/(?P<pk>[0-9]+)/close/$', views.close_task, name='close_task'),
    url(r'^task/(?P<pk>[0-9]+)/$', views.TaskView.as_view(), name = 'task_detail'),
    url(r'^task/(?P<pk>[0-9]+)/reopen/$', views.reopen_task, name='reopen_task'),
    url(r'^api/get_patient/$', views.get_patient, name='get_patient'),
    url(r'^api/get_diagnosis/$', views.get_diagnosis, name='get_diagnosis'),
    url(r'^api/get_snomed/$', views.get_snomed, name='get_snomed'),
    url(r'^api/get_treatment_option/$', views.get_treatment_option, name='get_treatment_option'),
    url(r'^api/get_standard_PE_results/$', views.get_standard_PE_results, name='get_standard_PE_results'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/choose_report/$', views.choose_encounter_report, name = 'choose_encounter_report'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/report/(?P<pk>[0-9]+)/$', views.view_encounter_report, name = 'view_encounter_report'),
    url(r'^treatment/(?P<treatmentid>[0-9]+)/choose_report/$', views.choose_treatment_report,
        name='choose_treatment_report'),
    url(r'^treatment/(?P<treatmentid>[0-9]+)/report/(?P<pk>[0-9]+)/$', views.view_treatment_report,
        name='view_treatment_report'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/treatment/(?P<treatmentid>[0-9]+)/attach_file/$', views.attach_file, name='encounter_treatment_attach_file'),
    url(r'^encounter/(?P<encounterid>[0-9]+)/assessment/(?P<assessmentid>[0-9]+)/treatment/(?P<treatmentid>[0-9]+)/attach_file/$', views.attach_file, name='treatment_attach_file'),
    ]

